Package1/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Package1/main/default/objects/Teacher__c/fields/Teacher_Email__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Email__c</fullName>
    <label>Teacher Email</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Package1/main/default/classes/TeacherController.cls
public class TeacherController {

    @AuraEnabled
    public static void insertNewTeacher(String teacherName, String teacherEmail) {
        //Teacher__c teacher = new Teacher__c (Name = teacherName, Teacher_Email__c = teacherEmail);

        try {
            Teacher__c teacher = new Teacher__c();
            teacher.Name = teacherName;
            teacher.Teacher_Email__c = teacherEmail;

            insert teacher;
        }
        catch (Exception ex) {
            System.debug('An Exception Occured');
        }
    }
}