HouseHogPackage/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <description>Real Estate Agency Affiliation</description>
    <label>Agency</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Agency__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <description>Reference to the 18-digit ID of the Agency&apos;s primary group. Lookup relationships to Group are not allowed.</description>
    <label>GroupId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/classes/AgencyHandler.cls
public class AgencyHandler {

    // Create Groups for each added agency, and add Group ID to agency field before insert.
    public static void CreateAgencyGroups(List<Agency__c> insertedAgencies) {

        Group[] agencyGroups = new Group[]{};

        for (Agency__c newAgency: insertedAgencies) {
            // Create new group for each agency
            Group newGroup = new Group();
            newGroup.Name = 'agencyGrp' + newAgency.name;
            newGroup.DoesIncludeBosses = false; 

            agencyGroups.add(newGroup);
        }
        
        Insert agencyGroups;
        
        // Convert to Map
        Map<String, Id> groupMap = new Map<String, Id>();
        for (Group agencyGroup : agencyGroups) {
            groupMap.put(agencyGroup.name, agencyGroup.Id);
        }

        // Add references to the added groups...
        for (Agency__c newAgency: insertedAgencies) {
            newAgency.GroupId__c = groupMap.get('agencyGrp' + newAgency.name);
        }
    }
}