Package1/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Package1/main/default/objects/Student__c/fields/Parent_Email__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email__c</fullName>
    <label>Parent Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Package1/main/default/classes/StudentController.cls
public class StudentController {

    // Inserts a new student into Salesforce with the student name, parent name, and parent email from the experience site

    @AuraEnabled
    public static void insertNewStudent(String studentName, String parentName, String parentEmail) {

        try {
            Student__c student = new Student__c();
            student.Name = studentName;
            student.Parent_Name__c = parentName;
            student.Parent_Email__c = parentEmail;

            insert student;
        }
        catch (Exception ex) {
            System.debug('An Exception Occured');
        }
    }
}