HouseHogPackage/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Real Estate uploaded by customers for listing or sale.</description>
    <label>Property</label>
    <nameField>
        <displayFormat>Property-{00000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>First and/or second lines of Property address.</description>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City that the Property is located in.</description>
    <label>City</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State that the Property is located in.</description>
    <inlineHelpText>Two-letter state code.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not For Sale</fullName>
                <default>true</default>
                <label>Not For Sale</label>
            </value>
            <value>
                <fullName>Listed</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Property's Zip code.</description>
    <inlineHelpText>Enter 5-digit code, or 9-digit code with hyphen separating first five digits from last four.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <description>An Account&apos;s interest in a Home.</description>
    <label>Prospect</label>
    <nameField>
        <displayFormat>Prospect-{000000}</displayFormat>
        <label>Prospect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Prospect__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account interested in the home.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Real estate that the Account is interested in.</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Type of interest in the home, and stage of a potential purchase.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Favorited</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HouseHogPackage/main/default/classes/ExperienceController.cls
public without sharing class ExperienceController {

    @AuraEnabled(cacheable=true)
    public static User GetUser() {

        id userId = UserInfo.getUserId();
        User u = [select id, name, email, contactId, accountId from User where id = :userId];
        //id getContactId = u.contactId;

        return u;
    }

    @AuraEnabled(cacheable=true)
    public static ID UserId() {
        return UserInfo.getUserId();
    }

    @AuraEnabled(cacheable=true)
    public static List<Prospect__c> UserProspects() {
        id userId = UserInfo.getUserId();
        User u = [select id, accountId from User where id = :userId];
        id userAccountId = u.accountId;

        Prospect__c[] allProspects = [
            SELECT id, Status__c, Property__r.Address__c, Property__r.City__c, Property__r.State__c, 
                Property__r.Zip_Code__c, Property__r.Status__c, FORMAT(Property__r.List_Price__c)
            FROM Prospect__c 
            WHERE Account__c = :userAccountId
        ];

        return allProspects;
    }

    @AuraEnabled(cacheable=true)
    public static List<Property__c> AllListedProperties() {
        Property__c[] allListed = [
            SELECT id, Status__c, Address__c, City__c, State__c, Zip_Code__c, FORMAT(List_Price__c)
            FROM Property__c 
            WHERE Status__c = 'Listed'
        ];

        return allListed;
    }

    // @AuraEnabled
    // public static Account GetAccountWithName(string name) {
    //     string filter = '%' + name + '%';
    //     return [SELECT name FROM Account WHERE name LIKE : filter LIMIT 1];
    // }
}