HouseHogPackage/main/default/objects/Account/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Primary Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

HouseHogPackage/main/default/objects/Account/fields/Primary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone_Number__c</fullName>
    <label>Primary Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

HouseHogPackage/main/default/objects/Account/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Agency__c/Agency__c.object-meta.xml
<CustomObject>
    <description>Real Estate Agency Affiliation</description>
    <label>Agency</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Agency__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City of agency headquarters.</description>
    <label>City</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Agency__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Agency&apos;s main email address.</description>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

HouseHogPackage/main/default/objects/Agency__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Main phone number for Agency.</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

HouseHogPackage/main/default/objects/Agency__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State of agency headquarters.</description>
    <inlineHelpText>Two-letter state code.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Agency__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Zip code of agency headquarters.</description>
    <inlineHelpText>Enter 5-digit code, or 9-digit code with hyphen separating first five digits from last four.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Real Estate uploaded by customers for listing or sale.</description>
    <label>Property</label>
    <nameField>
        <displayFormat>Property-{00000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>First and/or second lines of Property address.</description>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City that the Property is located in.</description>
    <label>City</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account who owns the property</description>
    <label>Property Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State that the Property is located in.</description>
    <inlineHelpText>Two-letter state code.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not For Sale</fullName>
                <default>true</default>
                <label>Not For Sale</label>
            </value>
            <value>
                <fullName>Listed</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>Property's Zip code.</description>
    <inlineHelpText>Enter 5-digit code, or 9-digit code with hyphen separating first five digits from last four.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <description>An Account&apos;s interest in a Home.</description>
    <label>Prospect</label>
    <nameField>
        <displayFormat>Prospect-{000000}</displayFormat>
        <label>Prospect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Prospect__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account interested in the home.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Real estate that the Account is interested in.</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Type of interest in the home, and stage of a potential purchase.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Favorited</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HouseHogPackage/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <description>Proxy object for realtor users.</description>
    <label>Realtor</label>
    <nameField>
        <displayFormat>Realtor-{00000}</displayFormat>
        <label>Realtor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Realtor__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Agency that the realtor is affiliated with.</description>
    <label>Agency</label>
    <referenceTo>Agency__c</referenceTo>
    <relationshipLabel>Realtors</relationshipLabel>
    <relationshipName>Realtors</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Realtor__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Realtor&apos;s primary phone number.</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

HouseHogPackage/main/default/objects/User/fields/Entity_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Entity_Affiliation__c</fullName>
    <description>Bank or Agency name that the user is affiliated with.</description>
    <label>Entity Affiliation</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

HouseHogPackage/main/default/objects/User/fields/User_Category__c.field-meta.xml
<CustomField>
    <fullName>User_Category__c</fullName>
    <defaultValue>NULL</defaultValue>
    <description>Is user a banker or a realtor?</description>
    <label>User Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Banker</fullName>
            </value>
            <value>
                <fullName>Realtor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HouseHogPackage/main/default/classes/DataFactory.cls
public class DataFactory {
    public static void CreateAgency() {
        Agency__c agency1 = new Agency__c(name = 'Realty Agency 1');
        agency1.Phone_Number__c = '456 777-2323';
        agency1.Email_Address__c = 'realtyagency1@fakemaildomain.com';
        agency1.Address__c = '123 Realty Agency Road';
        agency1.City__c = 'Reston';
        agency1.State__c = 'VA';
        agency1.Zip_Code__c = '13345';
        Insert agency1;
    }
    public static void CreateInternalUsers() {
        User[] internalUsers = new User[]{};
        User realtor1 = MakeUser('Realtor', 1, 'Realty Agency 1');
        internalUsers.add(realtor1);
        User realtor2 = MakeUser('Realtor', 2, 'Realty Agency 1');
        internalUsers.add(realtor2);
        Insert internalUsers;
    }
    public static void CreateAll() {
        Realtor__c[] realtors = [SELECT id FROM Realtor__c];
        if (realtors.size() < 2) {
            System.debug('Must have at least 2 realtor objects!');
            return;
        }

        Account[] newAccounts = new List<Account>();
        for (Integer i = 1; i <= 10; i++) {
            Account a = new Account();
            a.name = 'Account ' + i;
            a.Primary_Phone_Number__c = '1112223333';
            a.Primary_Email__c = 'account' + i + '@fakemail.com';

            if (Math.mod(i,2) == 1) {
                a.Realtor__c = realtors[0].id;
            } else {
                a.Realtor__c = realtors[1].id;
            }

            newAccounts.add(a);
        }
        Insert newAccounts;

        Contact[] newContacts = new List<Contact>();
        for (Integer i = 0; i < newAccounts.size(); i++) {
            Contact c = new Contact();
            c.firstName = 'Some';
            c.lastName = 'Contact' + i;
            c.AccountId = newAccounts[i].id;
            c.phone = newAccounts[i].Primary_Phone_Number__c;
            c.email = c.lastName + newAccounts[i].Primary_Email__c;
            newContacts.add(c);
        }
        Insert newContacts;

        Property__c[] newProperties = new List<Property__c>();
        String[] addresses = new String[]{
            '2764 Fake Street',
            '47629 City Town',
            '234 Notrealville Road',
            '654 Road Street',
            '2634 Mountain Valley Court',
            '785 River Road',
            '945 Forest Drive',
            '534 Lakewood Lane',
            '1742 Longway Road',
            '26 Pinewood Blvd.'
        };
        for (Integer i = 0; i < newAccounts.size(); i++) {
            Property__c p = new Property__c();
            p.Property_Owner__c = newAccounts[i].id;
            p.Address__c = addresses[i];
            p.City__c = 'Reston';
            p.State__c = 'VA';
            p.Zip_Code__c = '13245';
            p.Status__c = 'Listed';
            p.List_Price__c = 200000 + 15000*i;
            newProperties.add(p);
        }
        Insert newProperties;

        Prospect__c[] newProspects = new List<Prospect__c>();
        
        newProspects.add(MakeProspect(newAccounts[0].id, newProperties[3].id));
        newProspects.add(MakeProspect(newAccounts[0].id, newProperties[5].id));
        newProspects.add(MakeProspect(newAccounts[4].id, newProperties[3].id));
        newProspects.add(MakeProspect(newAccounts[4].id, newProperties[5].id));
        newProspects.add(MakeProspect(newAccounts[6].id, newProperties[5].id));
        newProspects.add(MakeProspect(newAccounts[9].id, newProperties[2].id));
        newProspects.add(MakeProspect(newAccounts[4].id, newProperties[7].id));
        newProspects.add(MakeProspect(newAccounts[3].id, newProperties[4].id));

        Insert newProspects;
    }
    public static Prospect__c MakeProspect(ID acctId, ID propertyId){
        Prospect__c p = new Prospect__c();
        p.Account__c = acctId;
        p.Property__c = propertyId;
        p.Status__c = 'Favorited';
        return p;
    }
    public static User MakeUser(String type, Integer baseNum , String entity) {
        User newUser = new User();
        newUser.User_Category__c = type;
        newUser.Alias = 'user' + baseNum;
        newUser.CommunityNickname = type + newUser.Alias;
        newUser.email = newUser.CommunityNickname + '@fakemail.com';
        newUser.phone = '111-222-4443';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.LocaleSidKey = 'en_US';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.Username = newUser.CommunityNickname + Math.random() * 100000 + '@fakemaildomain' + Math.random() * 100000 + '.com';
        newUser.firstName = type;
        newUser.lastName = 'User' + baseNum;
        newUser.Entity_Affiliation__c = entity;

        return newUser;
    }
}