HouseHogPackage/main/default/objects/Account/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>Real Estate uploaded by customers for listing or sale.</description>
    <label>Property</label>
    <nameField>
        <displayFormat>Property-{00000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account who owns the property</description>
    <label>Property Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <description>An Account&apos;s interest in a Home.</description>
    <label>Prospect</label>
    <nameField>
        <displayFormat>Prospect-{000000}</displayFormat>
        <label>Prospect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HouseHogPackage/main/default/objects/Prospect__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account interested in the home.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <description>Real estate that the Account is interested in.</description>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Prospects</relationshipLabel>
    <relationshipName>Prospects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Purchasing_Realtor__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Realtor representing the Account who wants to buy the home.</description>
    <label>Purchasing_Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Purchase Prospects</relationshipLabel>
    <relationshipName>Purchase_Prospects</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Prospect__c/fields/Selling_Realtor__c.field-meta.xml
<CustomField>
    <fullName>Selling_Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Sale Prospects</relationshipLabel>
    <relationshipName>Sale_Prospects</relationshipName>
    <type>Lookup</type>
</CustomField>

HouseHogPackage/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <description>Proxy object for realtor users.</description>
    <label>Realtor</label>
    <nameField>
        <displayFormat>Realtor-{00000}</displayFormat>
        <label>Realtor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HouseHogPackage/main/default/classes/ProspectHandler.cls
public class ProspectHandler {
    // BEFORE_INSERT
    // Add references to the realtors selling and purchasing the home
    public static void AttachRealtors(List<Prospect__c> insertedProspects) {
        Set<ID> accountIDs = new Set<ID>();
        Set<ID> propertyIDs = new Set<ID>();
        for (Prospect__c p : insertedProspects) {
            accountIDs.add(p.Account__c);
            propertyIDs.add(p.Property__c);
        }

        // Map properties to accounts
        Map<ID, ID> propertyToOwner = new Map<ID, ID>();
        for (Property__c property : [SELECT id, Property_Owner__c FROM Property__c WHERE id IN :propertyIDs]) {
            accountIDs.add(property.Property_Owner__c);
            propertyToOwner.put(property.id, property.Property_Owner__c);
        }

        // Map accounts to realtors
        Map<ID, ID> accountToRealtor = new Map<ID, ID>();
        for (Account a : [SELECT id, Realtor__c FROM Account WHERE id IN :accountIDs]) {
            accountToRealtor.put(a.id, a.Realtor__c);
        }
        
        // Update buying and selling realtor on each property
        for (Prospect__c p : insertedProspects) {
            p.Purchasing_Realtor__c = accountToRealtor.get(p.Account__c);

            ID propertyAccount = propertyToOwner.get(p.Property__c);
            p.Selling_Realtor__c = accountToRealtor.get(propertyAccount);
        }
    }

}